api_token_env: CROWDIN_TOKEN
project_id: 383539
branch: develop
preserve_hierarchy: true
files:
  - source: /iina/en.lproj/Localizable.strings
    ignore:
      - /iina/en.lproj/Settings*.strings
    translation: /iina/%osx_code%/%original_file_name%
